/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dbhelper;

import javax.swing.JFrame;

import dbhelper.guiStuff.LoginJFrame;

public class App {
    

    public static void main(String[] args) {
            LoginJFrame l = new LoginJFrame();
            l.setVisible(true);
            l.pack();
            l.setLocationRelativeTo(null);
            l.setResizable(false);
            
    }
}
